name: Build and Publish Homepage Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "k8s/**"
      - "README.md"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: dephekt/ci-templates/.github/workflows/docker-build.yml@main
    with:
      image_name: ghcr.io/dephekt/homepage-image
      upstream_image_search: hugomods/hugo
      upstream_name_short: hugo
      fetch_submodules: "recursive"
      build_args: |
        DOMAIN=${{ vars.DOMAIN }}
